apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-argocd-to-keycloak
  namespace: argocd
spec:
  description: Allow argocd pods to reach keycloak OIDC provider
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: keycloak
