apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakClient
metadata:
  name: synapse
  namespace: keycloak
spec:
  serverInstanceSelector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
  realm: platform
  clientId: synapse
  clientSecret:
    secretName: synapse-oidc-secret
    secretKey: SYNAPSE_OIDC_CLIENT_SECRET
  protocol: openid-connect
  DirectGrant: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  serviceAccountsEnabled: false
  publicClient: false
  alwaysDisplayInConsole: false
  attributes:
    client.secret.creation.method: uuid
  redirectUris:
    - "https://matrix.ebruno.fr/*"
  webOrigins:
    - "https://matrix.ebruno.fr"
  defaultClientScopes:
    - web-origins
    - acr
    - roles
    - profile
    - email
  optionalClientScopes:
    - address
    - phone
    - offline_access
    - microprofile-jwt
    - organization
