configuration:
  backupStorageLocation:
    - bucket: velero-backups
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://minio.velero.svc:9000
      name: default
      provider: aws
  volumeSnapshotLocation:
    - config:
        region: minio
      name: default
      provider: aws
credentials:
  name: velero-credentials
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = velero
      aws_secret_access_key = velero123456
  useSecret: true
deployNodeAgent: true
initContainers:
  - image: velero/velero-plugin-for-aws:v1.10.0
    name: velero-plugin-for-aws
    volumeMounts:
      - mountPath: /target
        name: plugins
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: true
schedules:
  daily:
    disabled: false
    schedule: 0 2 * * *
    template:
      includedNamespaces:
        - argocd
        - harbor
        - nexus
        - sonarqube
        - actions-runner-system
        - monitoring
      ttl: 168h
