configuration:
  backupStorageLocation:
    - bucket: velero-backups
      config:
        region: default
        s3ForcePathStyle: "true"
        s3Url: http://svc.garage.hrsrv.local:8252
      name: default
      provider: aws
  volumeSnapshotLocation:
    - config:
        region: default
      name: default
      provider: aws
credentials:
  name: velero-credentials
  useSecret: true
deployNodeAgent: true
initContainers:
  - image: velero/velero-plugin-for-aws:v1.10.0
    name: velero-plugin-for-aws
    volumeMounts:
      - mountPath: /target
        name: plugins
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: true
schedules:
  daily:
    disabled: false
    schedule: "0 2 * * *"
    template:
      includedNamespaces:
        - argocd
        - harbor
        - nexus
        - sonarqube
        - actions-runner-controller
        - monitoring
        - gitea
        - plane
        - apicurio
        - vault
        - external-secrets
        - ci
      ttl: 168h
