apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: link-shortener
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: link-shortener
      images:
        - imageName: harbor.ebruno.fr/link-shortener/link-shortener
          alias: link-shortener
          commonUpdateSettings:
            allowTags: "latest"
            forceUpdate: true
            updateStrategy: newest-build
            pullSecret: image-updater-creds
  writeBackConfig:
    method: git
