expose:
  ingress:
    enabled: false
  tls:
    enabled: false
  type: clusterIP
internalTLS:
  enabled: false
database:
  type: external
  external:
    host: harbor-postgresql.harbor.svc.cluster.local
    port: "5432"
    username: postgres
    coreDatabase: registry
    secretName: harbor-db-superuser
    passwordKey: postgres-password
    sslmode: disable
externalURL: https://harbor.ebruno.fr
persistence:
  enabled: true
  persistentVolumeClaim:
    chartmuseum:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: local-path
    database:
      accessMode: ReadWriteOnce
      size: 20Gi
      storageClass: local-path
    jobservice:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: local-path
    redis:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: local-path
    registry:
      accessMode: ReadWriteOnce
      size: 50Gi
      storageClass: local-path
  resourcePolicy: keep
resources:
  core:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  portal:
    requests:
      cpu: 50m
      memory: 128Mi
core:
  extraEnvVars:
    - name: HARBOR_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: harbor-oidc-secret
          key: Harboroidcclientsecret

service:
  type: ClusterIP
