apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-token-writer
  namespace: kube-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alertmanager-token-writer
  namespace: kube-prometheus
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager-token-writer
  namespace: kube-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alertmanager-token-writer
subjects:
  - kind: ServiceAccount
    name: alertmanager-token-writer
    namespace: kube-prometheus
