apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - remoteRef:
      key: oidc/oauth2-proxy
      property: clientSecret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
    secretKey: CLIENT_SECRET
  - remoteRef:
      key: oidc/oauth2-proxy
      property: cookieSecret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
    secretKey: COOKIE_SECRET
