apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        CLIENT_SECRET: '{{ .clientSecretProxy }}'
        COOKIE_SECRET: '{{ .cookieSecretOauth2Proxy }}'
  dataFrom:
    - extract:
        key: secret/data/keycloak
