when:
  branch: main

steps:
  - name: mvn-build
    image: docker.io/maven:3.9-eclipse-temurin-21
    environment:
      MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.artifact.threads=1"
    commands:
      - mvn clean package -DskipTests -Dquarkus.container-build.skip=true
    when:
      event: [push, pull_request]

  - name: kaniko-push
    image: gcr.io/kaniko-project/executor:debug-rootless
    commands:
      - |
        printf '{"auths":{"harbor.ebruno.fr":{"auth":"'"$(HARBOR_AUTH)"'"}}}' > /kaniko/.docker/config.json
        /kaniko/executor \
          --dockerfile=src/main/docker/Dockerfile.jvm \
          --context=dir:///${WOODPECKER_WORKSPACE} \
          --destination="harbor.ebruno.fr/link-shortener/link-shortener:${WOODPECKER_COMMIT}" \
          --destination="harbor.ebruno.fr/link-shortener/link-shortener:latest" \
          --skip-tls-verify-pull=true \
          --skip-tls-verify-dest=true \
          --single-snapshot \
          --reproducible=true \
          --cache=true \
          --cache-repo="harbor.ebruno.fr/link-shortener/cache"
    secrets: [HARBOR_AUTH]
    when:
      event: push

  - name: trivy-scan
    image: docker.io/aquasec/trivy:latest
    commands:
      - trivy image --severity HIGH,CRITICAL --exit-code 1 harbor.ebruno.fr/link-shortener/link-shortener:${WOODPECKER_COMMIT}
    when:
      event: push
