apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app-secrets
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: plane-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: secret/plane
        property: DATABASE_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: DATABASE_URL
    - remoteRef:
        key: secret/plane
        property: REDIS_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: REDIS_URL
    - remoteRef:
        key: secret/plane
        property: SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: SECRET_KEY
    - remoteRef:
        key: secret/plane
        property: LIVE_SERVER_SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: LIVE_SERVER_SECRET_KEY
    - remoteRef:
        key: secret/plane
        property: AMQP_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: AMQP_URL
