apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app-secrets
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: plane-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/plane
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/plane
        property: REDIS_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/plane
        property: SECRET_KEY
    - secretKey: LIVE_SERVER_SECRET_KEY
      remoteRef:
        key: secret/plane
        property: LIVE_SERVER_SECRET_KEY
    - secretKey: AMQP_URL
      remoteRef:
        key: secret/plane
        property: AMQP_URL
