apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-grafana
  namespace: kube-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
