apiVersion: v1
kind: Service
metadata:
  name: microcks-metrics
  namespace: microcks
  labels:
    app: microcks
    app.kubernetes.io/name: microcks
    microcks-metrics: "true"
spec:
  selector:
    app: microcks
    container: spring
    group: microcks
  ports:
    - name: http
      port: 9091
      targetPort: 9091
