apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: platform-collector
  namespace: alloy
spec:
  mode: sidecar
  replicas: 1

  observability:
    metrics:
      enableMetrics: true

  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 512
        send_batch_max_size: 1024
        timeout: 5s
      memory_limiter:
        check_interval: 1s
        limit_mib: 128
        spike_limit_mib: 64
      k8sattributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.deployment.name
            - k8s.node.name
        pod_association:
          - sources:
            - from: resource
              name: k8s.pod.ip
      resource:
        attributes:
          - key: cluster.name
            value: compute-lsis-2
            action: upsert

    exporters:
      otlp/tempo:
        endpoint: tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://kube-prometheus-kube-prome-prometheus.kube-prometheus.svc.cluster.local:9090/api/v1/write
      logging:
        verbosity: basic

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, k8sattributes, resource]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, k8sattributes, resource]
          exporters: [prometheusremotewrite]
