appName: microcks
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "true"
  prometheus.io/scrape: "true"
  prometheus.io/path: "/q/health"
features:
  async:
    enabled: false
ingresses: true
keycloak:
  enabled: true
  install: false
  privateUrl: http://keycloak-http.keycloak.svc.cluster.local:80
  url: keycloak.ebruno.fr
  realm: platform
microcks:
  generateCert: false
  ingressAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
  ingressClassName: traefik
  url: microcks.ebruno.fr
  grpcIngressClassName: traefik
  grpcIngressAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
mongodb:
  existingSecret: microcks-mongodb-connection
