appName: microcks
features:
  async:
    enabled: false
ingresses: true
keycloak:
  enabled: true
  generateCert: false
  ingressAnnotations:
    cert-manager.io/cluster-issuer: local-ca
    kubernetes.io/ingress.class: traefik
  ingressClassName: traefik
  ingressSecretRef: microcks-keycloak-tls
  install: true
  privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 768Mi
  url: keycloak-microcks.local
microcks:
  generateCert: false
  ingressAnnotations:
    cert-manager.io/cluster-issuer: local-ca
    kubernetes.io/ingress.class: traefik
  ingressClassName: traefik
  ingressSecretRef: microcks-tls
  url: microcks.local
