appName: microcks
features:
  async:
    enabled: false
ingresses: true
keycloak:
  enabled: true
  install: false
  privateUrl: http://keycloak-http.keycloak.svc.cluster.local:80
  url: keycloak.ebruno.fr
  realm: platform
microcks:
  generateCert: false
  ingressAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
  ingressClassName: traefik
  url: microcks.ebruno.fr
  grpcIngressClassName: traefik
  grpcIngressAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
mongodb:
  username: userM
  password: Ia3vPM8GN1D5SBlSxkf24TsnMyVLVhZi
  adminUsername: WOrYnZwXxeWsR80s
  adminPassword: H2kCABXN8jUCzFK48PVbvwPvN6gERkNGhC6lOx8S
