apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nexus
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://stevehipwell.github.io/helm-charts
    chart: nexus3
    targetRevision: 5.20.0

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nexus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
