apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
  ingressClassName: traefik
  rules:
    - host: cert-manager.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cert-manager-webhook
                port:
                  number: 443
  tls:
    - hosts:
        - cert-manager.ebruno.fr
