apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: backstage
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >-
    {
      "auths": {
        "harbor.ebruno.fr": {
          "username": "admin",
          "password": "Harbor12345",
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }
