apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-ingress
  namespace: kube-prometheus
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
spec:
  ingressClassName: traefik
  rules:
    - host: prometheus.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-kube-prome-prometheus
                port:
                  number: 9090
  tls:
    - hosts:
      - prometheus.ebruno.fr
