apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: link-shortener-proxy-headers
  namespace: link-shortener
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
      X-Forwarded-Host: link.ebruno.fr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: link-shortener-ingress
  namespace: link-shortener
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`link.ebruno.fr`)
      kind: Rule
      middlewares:
        - name: link-shortener-proxy-headers
      services:
        - name: link-shortener
          port: 80
  tls:
    certResolver: letsencrypt-ovh
