apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microcks-keycloak-ingress
  namespace: microcks
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-ovh
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: keycloak-microcks.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microcks-keycloak
                port:
                  number: 8080
  tls:
    - hosts:
        - keycloak-microcks.ebruno.fr
      secretName: microcks-keycloak-tls
