apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fwd-auth-pre-flight
  namespace: nexus
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
      - X-Forwarded-Email
      - X-Forwarded-Access-Token
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: browser-redirect
  namespace: nexus
spec:
  redirectRegex:
    regex: ^https://nexus\\.ebruno\\.fr(/.*)$
    replacement: https://keycloak.ebruno.fr/realms/platform/protocol/openid-connect/auth?client_id=proxy&redirect_uri=https://oauth2-proxy.ebruno.fr/oauth2/callback&scope=openid+profile+email&response_type=code&state=http://nexus.ebruno.fr/$$1
    permanent: false
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fwd-auth-chain
  namespace: nexus
spec:
  chain:
    middlewares:
      - name: fwd-auth-pre-flight
      - name: browser-redirect
