apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ingress
  namespace: nexus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nexus.ebruno.fr`) && PathPrefix(`/oauth2/`)
      priority: 20
      services:
        - name: oauth2-proxy
          namespace: oauth2-proxy
          port: 4180
    - kind: Rule
      match: Host(`nexus.ebruno.fr`) && Path(`/`)
      priority: 15
      middlewares:
        - name: oauth2-errors
        - name: fwd-auth
      services:
        - name: nexus-nexus3
          port: http
    - kind: Rule
      match: Host(`nexus.ebruno.fr`) && !PathPrefix(`/oauth2/`)
      priority: 10
      middlewares:
        - name: fwd-auth
      services:
        - name: nexus-nexus3
          port: http
  tls:
    certResolver: letsencrypt-ovh
