apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus-ingress
  namespace: nexus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nexus.ebruno.fr`)
      middlewares:
        - name: fwd-auth
      services:
        - name: nexus-nexus3
          port: http
  tls:
    certResolver: letsencrypt-ovh
