apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-lb
  namespace: sonarqube
spec:
  type: ExternalName
  externalName: oauth2-proxy.oauth2-proxy.svc.cluster.local
  ports:
    - name: http
      port: 4180
