apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pact-broker-ingress
  namespace: pact-broker
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
  ingressClassName: traefik
  rules:
    - host: pactbroker.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pact-broker
                port:
                  number: 80
  tls:
    - hosts:
        - pactbroker.ebruno.fr
