apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pact-broker-ingress
  namespace: pact-broker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-ovh
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: pactbroker.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pact-broker
                port:
                  number: 80
  tls:
    - hosts:
        - pactbroker.ebruno.fr
      secretName: pactbroker-tls
