apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pact-broker-ingress
  namespace: pact-broker
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pactbroker.ebruno.fr`)
      middlewares:
        - name: fwd-auth
      services:
        - name: pact-broker
          port: http
  tls:
    certResolver: letsencrypt-ovh
