apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: plane-backend-transport
  namespace: plane
spec:
  serverName: plane-backend
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plane-fw-web
  namespace: plane
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`plane.ebruno.fr`)
      kind: Rule
      services:
        - name: plane-web
          port: 3000
          scheme: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plane-redirect
  namespace: plane
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`plane.ebruno.fr`) && Header(`X-Forwarded-Port`, "3000")
      kind: Rule
      services:
        - name: plane-web
          port: 3000
    - match: Host(`plane.ebruno.fr`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: plane-web
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: plane
spec:
  redirectScheme:
    scheme: https
    permanent: true
