apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarqube-ingress
  namespace: sonarqube
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarqube.ebruno.fr`) && PathPrefix(`/oauth2/`)
      services:
        - name: oauth2-proxy
          namespace: oauth2-proxy
          port: 4180
    - kind: Rule
      match: Host(`sonarqube.ebruno.fr`) && !PathPrefix(`/oauth2/`)
      middlewares:
        - name: fwd-auth
      services:
        - name: sonarqube-sonarqube
          port: http
  tls:
    certResolver: letsencrypt-ovh
