apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ingress
  namespace: velero
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-ovh
spec:
  ingressClassName: traefik
  rules:
    - host: velero.ebruno.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: velero
                port:
                  number: 8085
  tls:
    - hosts:
      - velero.ebruno.fr
