apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apicurio-postgresql
  namespace: apicurio
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: apicurio-postgresql-auth
    template:
      type: Opaque
      data:
        username: "{{ .username | b64enc }}"
        password: "{{ .password | b64enc }}"
        postgresql-password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/postgresql/apicurio
      name: username
      property: username
    - key: secret/data/postgresql/apicurio
      name: password
      property: password
