apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apicurio-postgresql
  namespace: apicurio
spec:
  data:
  - remoteRef:
      key: secret/data/postgresql/apicurio
      property: username
    secretKey: username
  - remoteRef:
      key: secret/data/postgresql/apicurio
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: apicurio-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
        postgresql-password: '{{ .password | b64enc }}'
        username: '{{ .username | b64enc }}'
      type: Opaque
