apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-oidc-credentials
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: argocd-server-oidc-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        oidc.clientSecret: '{{ .clientSecretArgoCD }}'
        oidcClientSecret: '{{ .clientSecretArgoCD }}'
        OIDC_CLIENT_SECRET: '{{ .clientSecretArgoCD }}'
        ARGOCD_SERVER_OIDC_CLIENT_SECRET: '{{ .clientSecretArgoCD }}'
  data:
  - secretKey: clientSecretArgoCD
    remoteRef:
      key: keycloak
      property: clientSecretArgoCD
