apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: secret/data/backstage
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: backstage-secrets
    template:
      data:
        BACKSTAGE_JWT: '{{ .jwtSecret | b64enc }}'
        BACKSTAGE_GITEA_CLIENT_ID: '{{ .giteaClientID }}'
        BACKSTAGE_GITEA_CLIENT_SECRET: '{{ .giteaClientSecret }}'
        GITEA_TOKEN: '{{ .giteaToken }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
