apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: backstage-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        APP_CONFIG_database_connection_password: '{{ .password }}'
        BACKSTAGE_JWT: '{{ .jwtSecret | b64enc }}'
        GITEA_TOKEN: '{{ .giteaToken }}'
        BACKSTAGE_GITEA_CLIENT_ID: '{{ .giteaClientID }}'
        BACKSTAGE_GITEA_CLIENT_SECRET: '{{ .giteaClientSecret }}'
        BACKSTAGE_KEYCLOAK_CLIENT_ID: '{{ .keycloakClientID }}'
        BACKSTAGE_KEYCLOAK_CLIENT_SECRET: '{{ .keycloakClientSecret }}'
        GRAFANA_API_KEY: '{{ .grafanaApiKey }}'
  dataFrom:
    - extract:
        key: postgresql/backstage
    - extract:
        key: keycloak
    - extract:
        key: grafana/backstage
