apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-grafana-api-token
  namespace: backstage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: backstage-grafana-api-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        GRAFANA_API_KEY: '{{ .grafanaApiKey }}'
  dataFrom:
    - extract:
        key: grafana/backstage
