apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  data:
  - remoteRef:
      key: secret/data/postgresql/gitea
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitea-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
        postgresql-password: '{{ .password | b64enc }}'
      type: Opaque
