apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: postgresql/gitea
      metadataPolicy: None
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gitea-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
        postgresql-password: '{{ .password | b64enc }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
