apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-oidc
  namespace: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: gitea-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        CLIENT_SECRET_GITEA: '{{ .clientSecretGitea }}'
        client-id: gitea
        client-secret: '{{ .clientSecretGitea }}'
  dataFrom:
    - extract:
        key: keycloak
