apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: gitea-postgresql-auth
    template:
      type: Opaque
      data:
        password: "{{ .password | b64enc }}"
        postgresql-password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/postgresql/gitea
      name: password
      property: password
