apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: grafana-admin-password
    template:
      type: Opaque
      data:
        admin-password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/grafana
      name: password
      property: password
