apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secrets
  namespace: kube-prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: grafana-oidc-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: CLIENT_SECRET_GRAFANA
      remoteRef:
        key: oidc/grafana
        property: clientSecret
