apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secrets
  namespace: kube-prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: grafana-oidc-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        CLIENT_SECRET_GRAFANA: '{{ .clientSecretGrafana }}'
  dataFrom:
    - extract:
        key: keycloak
