apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  data:
  - remoteRef:
      key: secret/data/grafana
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: grafana-admin-password
    template:
      data:
        admin-password: '{{ .password | b64enc }}'
      type: Opaque
