apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-postgresql
  namespace: harbor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: harbor-postgresql-auth
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/instance: harbor
          app.kubernetes.io/part-of: harbor
      data:
        password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/postgresql/harbor
      name: password
      property: password
