apiVersion: v1
kind: Service
metadata:
  name: harbor-postgresql
  namespace: harbor
  labels:
    app: harbor-postgresql
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
  selector:
    app: harbor-postgresql
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: postgresql
    cnpg.io/cluster: harbor-db
    role: primary
