apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgresql
  namespace: harbor
spec:
  data:
  - remoteRef:
      key: postgresql/harbor
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: harbor-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
      metadata:
        labels:
          app.kubernetes.io/instance: harbor
          app.kubernetes.io/part-of: harbor
      type: Opaque
