apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc
  namespace: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: harbor-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        Harboroidcclientsecret: '{{ .clientSecretHarbor }}'
  dataFrom:
    - extract:
        key: secret/data/keycloak
