apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgresql
  namespace: harbor
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: postgresql/harbor
      metadataPolicy: None
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-postgresql-auth
    template:
      data:
        password: '{{ .password }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/instance: harbor
          app.kubernetes.io/part-of: harbor
      type: Opaque
