apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc
  namespace: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: harbor-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: Harboroidcclientsecret
      remoteRef:
        key: oidc/harbor
        property: clientSecret
