apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: keycloak-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        adminPassword: '{{ .adminPassword | b64enc }}'
        realmSecret: '{{ .realmSecret | b64enc }}'

  dataFrom:
    - extract:
        key: secret/data/keycloak
