apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: keycloak-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        adminPassword: '{{ .adminPassword }}'
        realmSecret: '{{ .realmSecret }}'
        CLIENT_SECRET_ARGOCD: '{{ .clientSecretArgoCD }}'
        CLIENT_SECRET_HARBOR: '{{ .clientSecretHarbor }}'
        CLIENT_SECRET_GITEA: '{{ .clientSecretGitea }}'
        CLIENT_SECRET_GRAFANA: '{{ .clientSecretGrafana }}'
        CLIENT_SECRET_VAULT: '{{ .clientSecretVault }}'
        CLIENT_SECRET_BACKSTAGE: '{{ .clientSecretBackstage }}'
        CLIENT_SECRET_PLANE: '{{ .clientSecretPlane }}'
        CLIENT_SECRET_MICROCKS: '{{ .clientSecretMicrocks }}'
        CLIENT_SECRET_NEXUS_SAML: '{{ .clientSecretNexusSaml }}'
        CLIENT_SECRET_SONARQUBE_SAML: '{{ .clientSecretSonarqubeSaml }}'
        userPasswordBruno: '{{ .userPasswordBruno }}'
        userPasswordCiRunner: '{{ .userPasswordCiRunner }}'

  data:
  - secretKey: adminPassword
    remoteRef:
      key: keycloak
      property: adminPassword
  - secretKey: realmSecret
    remoteRef:
      key: keycloak
      property: realmSecret
  - secretKey: clientSecretArgoCD
    remoteRef:
      key: oidc/argocd
      property: clientSecret
  - secretKey: clientSecretHarbor
    remoteRef:
      key: oidc/harbor
      property: clientSecret
  - secretKey: clientSecretGitea
    remoteRef:
      key: oidc/gitea
      property: clientSecret
  - secretKey: clientSecretGrafana
    remoteRef:
      key: oidc/grafana
      property: clientSecret
  - secretKey: clientSecretVault
    remoteRef:
      key: oidc/vault
      property: clientSecret
  - secretKey: clientSecretBackstage
    remoteRef:
      key: oidc/backstage
      property: clientSecret
  - secretKey: clientSecretPlane
    remoteRef:
      key: oidc/plane
      property: clientSecret
  - secretKey: clientSecretMicrocks
    remoteRef:
      key: oidc/microcks
      property: clientSecret
  - secretKey: clientSecretNexusSaml
    remoteRef:
      key: oidc/nexus
      property: clientSecret
  - secretKey: clientSecretSonarqubeSaml
    remoteRef:
      key: oidc/sonarqube
      property: clientSecret
  - secretKey: userPasswordBruno
    remoteRef:
      key: keycloak
      property: userPasswordBruno
  - secretKey: userPasswordCiRunner
    remoteRef:
      key: keycloak
      property: userPasswordCiRunner
