apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: keycloak-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        adminPassword: '{{ .adminPassword | b64enc }}'
        realmSecret: '{{ .realmSecret | b64enc }}'
        CLIENT_SECRET_ARGOCD: '{{ .clientSecretArgoCD }}'
        CLIENT_SECRET_HARBOR: '{{ .clientSecretHarbor }}'
        CLIENT_SECRET_GITEA: '{{ .clientSecretGitea }}'
        CLIENT_SECRET_GRAFANA: '{{ .clientSecretGrafana }}'
        CLIENT_SECRET_VAULT: '{{ .clientSecretVault }}'
        CLIENT_SECRET_BACKSTAGE: '{{ .clientSecretBackstage }}'
        CLIENT_SECRET_PLANE: '{{ .clientSecretPlane }}'
        CLIENT_SECRET_MICROCKS: '{{ .clientSecretMicrocks }}'

  dataFrom:
    - extract:
        key: secret/data/keycloak
