apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        username: 'a2V5Y2xvYWs='
        password: '{{ .password | b64enc }}'
  dataFrom:
    - extract:
        key: secret/data/postgresql/keycloak
