apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: link-shortener-db-secret
  namespace: link-shortener
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: link-shortener-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        url: '{{ .url }}'
        username: '{{ .username }}'
        password: '{{ .password }}'
  dataFrom:
    - extract:
        key: postgresql/link-shortener
