apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: linkshortener
  namespace: link-shortener
spec:
  cluster:
    name: link-shortener-db
  comment: link-shortener application role
  connectionLimit: -1
  name: linkshortener
  ensure: present
  login: true
  passwordSecret:
    name: link-shortener-db-credentials
