apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-db
  namespace: synapse
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "200"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
