apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-mongodb-connection
  namespace: microcks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: microcks-mongodb-connection
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
        adminUsername: '{{ .adminUsername }}'
        adminPassword: '{{ .adminPassword }}'
  data:
  - secretKey: username
    remoteRef:
      key: microcks
      property: username
  - secretKey: password
    remoteRef:
      key: microcks
      property: password
  - secretKey: adminUsername
    remoteRef:
      key: microcks
      property: adminUsername
  - secretKey: adminPassword
    remoteRef:
      key: microcks
      property: adminPassword
