apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-oidc
  namespace: microcks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: microcks-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: oidc/microcks
        property: clientSecret
