apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-oidc
  namespace: microcks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: microcks-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        CLIENT_SECRET: '{{ .clientSecretMicrocks }}'
  dataFrom:
    - extract:
        key: keycloak
