apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nexus-db
  namespace: nexus
spec:
  instances: 1
  bootstrap:
    initdb:
      database: app
      owner: app
  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://backups/nexus-db
      endpointURL: http://garage.garage.svc:3900
      s3Credentials:
        accessKeyId:
          name: nexus-backup-s3
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: nexus-backup-s3
          key: AWS_SECRET_ACCESS_KEY
        region:
          name: nexus-backup-s3
          key: AWS_REGION
  storage:
    size: 20Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "300"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
