apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-postgresql
  namespace: nexus
spec:
  data:
  - remoteRef:
      key: secret/data/postgresql/nexus
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: nexus-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
      metadata:
        labels:
          app.kubernetes.io/instance: nexus
          app.kubernetes.io/part-of: nexus
      type: Opaque
