apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-postgresql
  namespace: nexus
spec:
  dataFrom:
  - extract: postgresql/nexus
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: nexus-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
        username: 'bmV4dXM='
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/instance: nexus
          app.kubernetes.io/part-of: nexus
      type: Opaque
