apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-postgresql
  namespace: nexus
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: nexus-postgresql-auth
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/instance: nexus
          app.kubernetes.io/part-of: nexus
      data:
        password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/postgresql/nexus
      name: password
      property: password
