apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pact-broker-postgresql
  namespace: pact-broker
spec:
  dataFrom:
  - extract:
      key: postgresql/pact-broker
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pact-broker-db
    template:
      data:
        password: '{{ .password }}'
        username: 'pactbroker'
        user-password: '{{ .password }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/instance: pact-broker
          app.kubernetes.io/part-of: pact-broker
      type: Opaque
