apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pact-broker-auth
  namespace: pact-broker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: pact-broker-basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        write-username: "{{ .username }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/pact-broker
        property: username
