apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-oidc
  namespace: plane
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: plane-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        # Django secret keys (from Helm values defaults)
        SECRET_KEY: '60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5'
        LIVE_SERVER_SECRET_KEY: 'htbqvBJAgpm9bzvf3r4urJer0ENReatceh'

        # Connection URLs (from Helm env values)
        DATABASE_URL: 'postgresql://plane:plane2026Secure@plane-postgresql.plane.svc.cluster.local:5432/plane'
        REDIS_URL: 'redis://plane-redis.plane.svc.cluster.local:6379/'
        AMQP_URL: 'amqp://plane:plane@plane-rabbitmq.plane.svc.cluster.local/'

        # OIDC configuration
        SOCIAL_AUTH_OIDC_KEY: 'plane'
        SOCIAL_AUTH_OIDC_SECRET: '{{ .clientSecretPlane }}'
        SOCIAL_AUTH_OIDC_ENTERPRISE_HOST: 'https://keycloak.ebruno.fr/realms/platform'
        SOCIAL_AUTH_OIDC_EDITION: 'enterprise'
        SOCIAL_AUTH_OIDC_VERIFY_AUTH_CODE: 'True'
        SOCIAL_AUTH_EXTRA_USERDATA_FIELDS: 'email,name,sub'
  dataFrom:
    - extract:
        key: secret/data/keycloak
