apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-postgresql
  namespace: plane
spec:
  data:
  - remoteRef:
      key: secret/postgresql/plane
      property: password
    secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: plane-postgresql-auth
    template:
      data:
        password: '{{ .password | b64enc }}'
        postgresql-password: '{{ .password | b64enc }}'
      type: Opaque
