apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-oidc
  namespace: plane
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: plane-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: SOCIAL_AUTH_OIDC_SECRET
    remoteRef:
      key: oidc/plane
      property: clientSecret
  - secretKey: SECRET_KEY
    remoteRef:
      key: plane/general
      property: secretKey # Will need to inject these base plane secrets too
  - secretKey: LIVE_SERVER_SECRET_KEY
    remoteRef:
      key: plane/general
      property: liveServerSecretKey
  - secretKey: DATABASE_URL
    remoteRef:
      key: plane/db
      property: url
  - secretKey: REDIS_URL
    remoteRef:
      key: plane/redis
      property: url
  - secretKey: AMQP_URL
    remoteRef:
      key: plane/redis
      property: url
  - secretKey: WEB_URL
    remoteRef:
      key: plane/general
      property: webUrl
