apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: plane-db
  namespace: plane
spec:
  instances: 1
  bootstrap:
    initdb:
      database: plane
      owner: plane
  backup:
    volumeSnapshot:
      className: test-snapshot-class
      online: true
  storage:
    size: 20Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "200"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
