apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-postgresql
  namespace: plane
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: plane-postgresql-auth
    template:
      type: Opaque
      data:
        password: "{{ .password | b64enc }}"
        postgresql-password: "{{ .password | b64enc }}"
  data:
    - key: secret/data/postgresql/plane
      name: password
      property: password
