apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-saml
  namespace: sonarqube
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: keycloak
      metadataPolicy: None
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-oidc-secret
    template:
      data:
        secret.properties: |
          sonar.auth.saml.enabled=true
          sonar.auth.saml.applicationId=sonarqube
          sonar.auth.saml.providerName=Keycloak
          sonar.auth.saml.providerId=https://keycloak.ebruno.fr/realms/devops
          sonar.auth.saml.loginUrl=https://keycloak.ebruno.fr/realms/devops/protocol/saml
          sonar.auth.saml.signature.enabled=true
          sonar.auth.saml.certificate.secured={{ .devopsRealmSigningCert }}
          sonar.auth.saml.sp.privateKey.secured={{ .sonarqubePrivateKeySecured }}
          sonar.auth.saml.sp.certificate.secured={{ .sonarqubeCertificateSecured }}
          sonar.auth.saml.user.login=login
          sonar.auth.saml.user.name=name
          sonar.auth.saml.user.email=email
          sonar.auth.saml.group.name=groups
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
