apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-credentials
  namespace: sonarqube
  labels:
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/part-of: sonarqube
spec:
  dataFrom:
  - extract:
      key: sonarqube
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-credentials
    template:
      data:
        currentPassword: 'admin'
        password: '{{ .adminPassword }}'
        sonar-secret.txt: '{{ .cryptoSecret }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/instance: sonarqube
          app.kubernetes.io/part-of: sonarqube
      type: Opaque
