apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
  labels:
    app: sonarqube-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: sonarqube-postgresql
    cnpg.io/cluster: sonarqube-db
    role: primary
