apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
spec:
  dataFrom:
  - extract:
      key: postgresql/sonarqube
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-postgresql
    template:
      data:
        password: '{{ .password }}'
        postgresql-password: '{{ .password }}'
        postgresql-username: '{{ .username }}'
        sonaruser: '{{ .username }}'
        username: '{{ .username }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/instance: sonarqube
          app.kubernetes.io/part-of: sonarqube
      type: Opaque
