apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-monitoring-password
  namespace: sonarqube
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterStore
    name: vault
  target:
    name: sonarqube-monitoring-password
    template:
      type: Opaque
      data:
        monitoring-passcode: "{{ .passcode | b64enc }}"
  data:
    - key: secret/data/sonarqube/monitoring
      name: passcode
      property: passcode
