apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  instances: 1
  storage:
    size: 20Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "400"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
