apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-monitoring-password
  namespace: sonarqube
spec:
  data:
  - remoteRef:
      key: sonarqube/monitoring
      property: adminPassword
    secretKey: passcode
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: sonarqube-monitoring-password
    template:
      data:
        monitoring-passcode: '{{ .passcode | b64enc }}'
      type: Opaque
