apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-oidc
  namespace: sonarqube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: sonarqube-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        client-id: '{{ .clientIdSonarqube }}'
        client-secret: '{{ .clientSecretSonarqube }}'
        secret.properties: |
          sonar.authentication.sso.provider=open_id_connect
          sonar.auth.sso.allowUserCreation=true
          sonar.auth.sso.provider.open_id_connect.url=https://sonarqube.ebruno.fr/oauth2/callback
          sonar.auth.sso.provider.open_id_connect.provider.url=https://keycloak.ebruno.fr/realms/platform
          sonar.auth.sso.provider.open_id_connect.provider.clientId={{ .clientIdSonarqube }}
          sonar.auth.sso.provider.open_id_connect.provider.clientSecret={{ .clientSecretSonarqube }}
          sonar.auth.sso.provider.open_id_connect.provider.authorizationEndpoint=https://keycloak.ebruno.fr/realms/platform/protocol/openid-connect/auth
          sonar.auth.sso.provider.open_id_connect.provider.tokenEndpoint=https://keycloak.ebruno.fr/realms/platform/protocol/openid-connect/token
          sonar.auth.sso.provider.open_id_connect.provider.tokenIntrospectionEndpoint=https://keycloak.ebruno.fr/realms/platform/protocol/openid-connect/token/introspect
          sonar.auth.sso.provider.open_id_connect.provider.userInfoEndpoint=https://keycloak.ebruno.fr/realms/platform/protocol/openid-connect/userinfo
          sonar.auth.sso.provider.open_id_connect.groups.attribute=groups
          sonar.auth.sso.provider.open_id_connect.groups.group-admins.platform-admins=__builtin_organization_administrator__
          sonar.auth.sso.provider.open_id_connect.groups.group-admins.platform-engineers=__builtin_organization_administrator__
          sonar.auth.sso.provider.open_id_connect.groups.group-users.developers=__builtin_user__
          sonar.auth.sso.provider.open_id_connect.groups.group-users.readonly=__builtin_user__
  dataFrom:
    - extract:
        key: keycloak
