apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-monitoring-password
  namespace: sonarqube
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: sonarqube/monitoring
      metadataPolicy: None
      property: adminPassword
    secretKey: passcode
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-monitoring-password
    template:
      data:
        monitoring-passcode: '{{ .passcode | b64enc }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
