apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  instances: 1
  database: sonardb
  bootstrap:
    initdb:
      database: app
      owner: app
  roles:
    - name: app
      ensure: present
      login: true
      passwordSecretRef:
        name: sonarqube-postgresql
        key: postgresql-password
  backup:
    volumeSnapshot:
      snapshotClass: test-snapshot-class
      onlineConfiguration:
        process:
          preBackup: "select pg_start_backup('cnpg');"
          postBackup: "select pg_stop_backup();"
  storage:
    size: 20Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "400"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
