apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-oidc
  namespace: synapse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: synapse-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        # Synapse reads these env vars for OIDC config
        SYNAPSE_OIDC_ISSUER: 'https://keycloak.ebruno.fr/realms/platform'
        SYNAPSE_OIDC_CLIENT_ID: 'synapse'
        SYNAPSE_OIDC_CLIENT_SECRET: '{{ .clientSecretSynapse }}'
  dataFrom:
    - extract:
        key: keycloak
