apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-oidc-secrets
  namespace: vault
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: vault-oidc-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        OIDC_CLIENT_SECRET: '{{ .clientSecretVault }}'
  dataFrom:
    - extract:
        key: keycloak
