apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: velero/s3
      metadataPolicy: None
      property: accessKey
    secretKey: accessKey
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: velero/s3
      metadataPolicy: None
      property: secretKey
    secretKey: secretKey
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: velero-credentials
    template:
      data:
        cloud: '[default]

          aws_access_key_id = {{ .accessKey }}

          aws_secret_access_key = {{ .secretKey }}

          '
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
