apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  data:
  - remoteRef:
      key: secret/data/velero/s3
      property: accessKeyId
    secretKey: accessKeyId
  - remoteRef:
      key: secret/data/velero/s3
      property: secretAccessKey
    secretKey: secretAccessKey
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: velero-credentials
    template:
      data:
        cloud: '[default]

          aws_access_key_id = {{ .accessKeyId }}

          aws_secret_access_key = {{ .secretAccessKey }}

          '
      type: Opaque
