apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-oidc
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: woodpecker-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        WOODPECKER_ADMIN: '{{ .woodpeckerAdmin }}'
        WOODPECKER_OAUTH_CLIENT_ID: 'woodpecker'
        WOODPECKER_OAUTH_CLIENT_SECRET: '{{ .clientSecretWoodpecker }}'
        WOODPECKER_OPEN_ID_CLIENT: 'woodpecker'
        WOODPECKER_OPEN_ID_SECRET: '{{ .clientSecretWoodpecker }}'
  dataFrom:
    - extract:
        key: keycloak
