apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-db-superuser
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: woodpecker-db-superuser
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        username: '{{ .dbUsernameWoodpecker }}'
        password: '{{ .dbPasswordWoodpecker }}'
        WOODPECKER_DATABASE_USER: '{{ .dbUsernameWoodpecker }}'
        WOODPECKER_DATABASE_PASSWORD: '{{ .dbPasswordWoodpecker }}'
  dataFrom:
    - extract:
        key: postgresql
