apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-server-secret
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: woodpecker-server-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WOODPECKER_SECRET
      remoteRef:
        key: woodpecker/server
        property: secret
    - secretKey: WOODPECKER_GRPC_SECRET
      remoteRef:
        key: woodpecker/server
        property: grpcSecret
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: woodpecker/server
        property: agentSecret
