apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: woodpecker-db
  namespace: ci
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: woodpecker
      owner: woodpecker
  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://backups/woodpecker-db
      endpointURL: http://garage.garage.svc:3900
      s3Credentials:
        accessKeyId:
          name: woodpecker-backup-s3
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: woodpecker-backup-s3
          key: AWS_SECRET_ACCESS_KEY
        region:
          name: woodpecker-backup-s3
          key: AWS_REGION
  postgresql:
    parameters:
      max_connections: "200"
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
