apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-oidc
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: woodpecker-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WOODPECKER_OPEN_ID_SECRET
      remoteRef:
        key: oidc/woodpecker
        property: clientSecret
    - secretKey: WOODPECKER_ADMIN
      remoteRef:
        key: oidc/woodpecker
        property: adminUser
