apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-postgresql
  namespace: ci
spec:
  dataFrom:
  - extract:
      key: postgresql/woodpecker
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: woodpecker-db-vault
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        fqdn-uri: 'postgresql://woodpecker:{{ .password | replace "/" "%2F" | replace "+" "%2B" }}@woodpecker-postgresql.ci.svc.cluster.local:5432/woodpecker?sslmode=require'
        WoodpeckerDBUrl: 'postgresql://woodpecker:{{ .password | replace "/" "%2F" | replace "+" "%2B" }}@woodpecker-postgresql.ci.svc.cluster.local:5432/woodpecker?sslmode=require'
        password: '{{ .password }}'
        username: '{{ .username }}'
