apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-gitea-oauth
  namespace: ci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: woodpecker-gitea-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: id
      remoteRef:
        key: gitea/woodpecker-oauth
        property: clientId
    - secretKey: secret
      remoteRef:
        key: gitea/woodpecker-oauth
        property: clientSecret
