replicaCount: 1

image:
  repository: apicurio/apicurio-registry-kafkasql
  pullPolicy: IfNotPresent

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

configerProvider: SQL
api:
  url: /api/rest

sql:
  datasource:
    pool:
      max-size: 20
