apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-web
  namespace: element
  labels:
    app: element-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: element-web
    spec:
      containers:
        - name: element-web
          image: vectorim/element-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: WEBAPP_BASE_URL
              value: https://element.ebruno.fr
            - name: NGINX_UPSTREAM_SERVER_URL
              value: synapse.synapse.svc.cluster.local
            - name: NGINX_UPSTREAM_SERVER_PORT
              value: "8008"
          volumeMounts:
            - name: element-web-config
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: element-web-config
          configMap:
            name: element-web-config
