apiVersion: v1
data:
  oidc.config: |
    issuer: https://keycloak.ebruno.fr/realms/platform
    clientID: argocd
    clientSecret: $ARGOCD_SERVER_OIDC_CLIENT_SECRET
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true
  sso: "true"
  sso.providers: oidc
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
