apiVersion: v1
data:
  timeout.reconciliation: 180s
  url: https://argocd.ebruno.fr
  cluster.inClusterEnabled: 'true'
  oidc.config: "issuer: https://keycloak.ebruno.fr/realms/platform\nclientID: argocd\n\
    clientSecret: $CLIENT_SECRET_ARGOCD\nrequestedScopes:\n  - openid\n  - profile\n\
    \  - email\nrequestedIDTokenClaims: {}\n"
  rbac.policy.default: "# Keycloak groups \u2192 ArgoCD roles\np, g:/platform-admins,\
    \ role:admin\np, g:/platform-engineers, role:projects-admin\np, g:/developers,\
    \ role:readonly\np, g:/readonly, role:readonly\np, g:/developers/qa-team, role:readonly\n\
    p, g:/developers/security-team, role:readonly\n"
  sso: 'true'
  sso.providers: oidc
  resource.customizations.health: "external-secrets.io/ExternalSecret:\n  health.lua:\
    \ |\n    hs = { status = \"Healthy\", message = \"Managed by External Secrets\" }\n\
    postgresql.cnpg.io/Cluster:\n  health.lua:\
    \ |\n    hs = { status = \"Healthy\", message = \"Managed by CloudNativePG\" }\n\
    traefik.io/Middleware:\n  health.lua: |\n    hs = { status = \"Healthy\",\
    \ message = \"Managed by Traefik\" }\ntraefik.io/ServersTransport:\n  health.lua:\
    \ |\n    hs = { status = \"Healthy\", message = \"Managed by Traefik\" }\nopentelemetry.io/OpenTelemetryCollector:\n\
    \  health.lua: |\n    hs = { status = \"Healthy\", message = \"Managed by OpenTelemetry Operator\" }\n"
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
