apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: ssh
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
      name: ssh
  selector:
    app.kubernetes.io/name: gitea
