apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-keycloak-dockerfile
  namespace: backstage
data:
  Dockerfile: |
    FROM ghcr.io/backstage/backstage:latest

    USER root

    RUN cd /app && \
        yarn config set httpTraceEnabled true && \
        yarn add @backstage/plugin-auth-backend-module-keycloak-provider --mode=skip-build && \
        sed -i "/plugin-auth-backend-module-guest-provider/a backend.add(import('@backstage\/plugin-auth-backend-module-keycloak-provider'));" /app/packages/backend/dist/index.cjs.js && \
        chown -R 1001:1001 /app

    USER 1001
