apiVersion: batch/v1
kind: Job
metadata:
  name: build-backstage-keycloak
  namespace: backstage
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      initContainers:
        - name: prepare-docker-config
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              mkdir -p /kaniko/.docker
              printf '{"auths":{"harbor.ebruno.fr":{"username":"admin","password":"Harbor12345","auth":"YWRtaW46SGFyYm9yMTIzNDU="}}}' > /kaniko/.docker/config.json
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.23.2
          args:
            - --dockerfile=/workspace/Dockerfile
            - --context=dir:///workspace
            - --destination=harbor.ebruno.fr/library/backstage-keycloak:latest
            - --insecure
            - --skip-tls-verify
            - --single-snapshot
          volumeMounts:
            - name: dockerfile
              mountPath: /workspace
            - name: docker-config
              mountPath: /kaniko/.docker
      restartPolicy: Never
      backoffLimit: 3
  volumes:
    - name: dockerfile
      configMap:
        name: backstage-keycloak-dockerfile
    - name: docker-config
      emptyDir: {}
