runnerScaleSetName: ebpro-org
githubConfigUrl: https://github.com/ebpro
githubConfigSecret: arc-github-creds
scaleSetLabels:
  - linux
  - x64
minRunners: 1
maxRunners: 2
containerMode:
  type: dind
controllerServiceAccount:
  namespace: actions-runner-controller
  name: arc-controller
template:
  spec:
    imagePullSecrets:
      - name: docker-hub-registry
    containers:
      - name: runner
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
listenerTemplate:
  spec:
    imagePullSecrets:
      - name: docker-hub-registry
    containers:
      - name: listener
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
