runnerScaleSetName: ebpro-org
githubConfigUrl: https://github.com/ebpro
githubConfigSecret: arc-github-creds
scaleSetLabels:
  - self-hosted
  - linux
  - x64
minRunners: 1
maxRunners: 3
dind:
  image: docker:28-dind
containerMode:
  type: dind
controllerServiceAccount:
  namespace: actions-runner-controller
  name: arc-controller
template:
  spec:
    imagePullSecrets:
      - name: docker-hub-registry
      - name: harbor-registry-secret
    containers:
      - name: runner
        image: harbor.ebruno.fr/quarkus-microservices/quarkus-ci-runner:v1.1.0
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
listenerTemplate:
  spec:
    imagePullSecrets:
      - name: docker-hub-registry
    containers:
      - name: listener
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
