fullnameOverride: tempo
replicas: 1
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: local-path
service:
  type: ClusterIP
serviceMonitor:
  enabled: true
tempo:
  memBallastSizeMbs: 0
  reportingEnabled: false
  auth:
    enabled: false
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  overrides: {}
  search:
    attributes:
      - app
      - namespace
      - pod
      - container
      - component
      - cluster
  server:
    http_listen_port: 3200
    http_server_read_timeout: 60s
    http_server_write_timeout: 60s
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-kube-prome-prometheus.kube-prometheus.svc.cluster.local:9090/api/v1/write
  compactor:
    block:
      retrieval_duration: 30m
      working_dir: /var/tempo/traces/block
  distributor:
    ring:
      kvstore:
        store: memberlist
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
config: |
  memberlist:
    cluster_label: "tempo.tempo"
  multitenancy_enabled: false
  usage_report:
    reporting_enabled: false
  compactor:
    compaction:
      block_retention: 24h
  distributor:
    enable_metrics_generator_ring: true
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
  ingester: {}
  server:
    http_listen_port: 3200
    http_server_read_timeout: 60s
    http_server_write_timeout: 60s
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  querier: {}
  query_frontend: {}
  overrides:
    defaults: {}
    per_tenant_override_config: /conf/overrides.yaml
  metrics_generator:
    storage:
      path: "/tmp/tempo"
      remote_write:
        - url: http://kube-prometheus-kube-prome-prometheus.kube-prometheus.svc.cluster.local:9090/api/v1/write
    traces_storage:
      path: "/tmp/traces"
