fullnameOverride: tempo
replicas: 1
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: local-path
service:
  type: ClusterIP
serviceMonitor:
  enabled: true
tempo:
  memBallastSizeMbs: 0
  reportingEnabled: false
  auth:
    enabled: false
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  overrides: {}
  search:
    attributes:
      - app
      - namespace
      - pod
      - container
      - component
      - cluster
  server:
    http_listen_port: 3200
    http_server_read_timeout: 60s
    http_server_write_timeout: 60s
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-kube-prome-prometheus.kube-prometheus.svc.cluster.local:9090/api/v1/write
  compactor:
    block:
      retrieval_duration: 30m
      working_dir: /var/tempo/traces/block
  distributor:
    ring:
      kvstore:
        store: memberlist
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
