apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-matrix-config
  namespace: kube-prometheus
spec:
  receivers:
    - name: 'matrix'
      matrix:
        webhook:
          uri: 'http://synapse.synapse.svc.cluster.local:8008'
          tlsConfig:
            insecureSkipVerify: true
        tokenSecret:
          name: alertmanager-matrix-token
          key: matrix-access-token
        tokenKeyFile: /etc/alertmanager-token/matrix-access-token
        roomID: '!kLasyTgOvpGTAGTEBU:matrix.ebruno.fr'
        username: alertmanager
        sendResolved: true
  route:
    receiver: 'matrix'
    groupBy:
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: 'matrix'
        matchers:
          - alertname =~ "Watchdog"
