apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-matrix-config
  namespace: kube-prometheus
spec:
  receivers:
    - name: 'matrix'
      webhookConfigs:
        - url: 'http://alertmanager-matrix-webhook.kube-prometheus.svc.cluster.local:8080'
          sendResolved: true
          maxAlerts: 100
  route:
    receiver: 'matrix'
    groupBy:
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: 'matrix'
        matchers:
          - alertname =~ "Watchdog"
