apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: harbor
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: gitea
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: external-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: kube-prometheus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: loki
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: nexus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: plane
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: sonarqube
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: garage
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: vault
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: microcks
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: tempo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: alloy
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: velero
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: actions-runner-controller
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: apicurio
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-registry
  namespace: pact-broker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
