apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-harbor-pull
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: pull
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: backstage-harbor-pull
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
      data:
        ".dockerconfigjson": '{"auths":{"harbor.ebruno.fr":{"username":{{ .username | toJson }},"password":{{ .password | toJson }},"auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}'
  dataFrom:
    - extract:
        key: secret/harbor/backstage
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
