apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-server
  namespace: ci
data:
  STORAGE_DRIVER: "s3"
  STORAGE_S3_BUCKET: "actions-cache"
  STORAGE_S3_SOCKET_TIMEOUT_MS: "10000"
  AWS_REGION: "garage"
  AWS_ENDPOINT_URL: "http://garage.garage.svc.cluster.local:3900"
  DB_DRIVER: "sqlite"
  DB_SQLITE_PATH: "/data/cache.db"
  API_BASE_URL: "http://cache-server.ci.svc:3000"
  CACHE_CLEANUP_OLDER_THAN_DAYS: "90"
  ENABLE_DIRECT_DOWNLOADS: "false"
