apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cache-server
  namespace: ci
  labels:
    app.kubernetes.io/name: cache-server
    app.kubernetes.io/component: ci-cache
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cache-server
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: ci/actions-cache-server
        property: accessKeyId
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        key: ci/actions-cache-server
        property: secretAccessKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: AWS_SECRET_ACCESS_KEY
    - remoteRef:
        key: ci/actions-cache-server
        property: managementApiKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: MANAGEMENT_API_KEY
