apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-backstage-creds
  namespace: ci
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: ci-push
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: woodpecker-harbor-backstage
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: secret/harbor/backstage
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: harbor_robot_user
    - remoteRef:
        key: secret/harbor/backstage
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: harbor_robot_pass
