apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: actions-runner-controller
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://charts.actions-runner-controller.io
    chart: actions-runner-controller
    targetRevision: latest
    helm:
      valueFiles:
        - ../releases/actions-runner-controller/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
