apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nfs-client
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://charts.nfs-client.io
    chart: nfs-client
    targetRevision: latest
    helm:
      valueFiles:
        - ../releases/nfs-client/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-client

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
