apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: pact-broker
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://charts.pact-broker.io
    chart: pact-broker
    targetRevision: latest
    helm:
      valueFiles:
        - ../releases/pact-broker/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
