apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vault
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://charts.vault.io
    chart: vault
    targetRevision: latest
    helm:
      valueFiles:
        - ../releases/vault/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
