planeVersion: v1.2.0

dockerRegistry:
  enabled: false

ingress:
  enabled: false

redis:
  local_setup: false

postgres:
  local_setup: false

rabbitmq:
  local_setup: false

env:
  remote_redis_url: redis://plane-redis.plane.svc.cluster.local:6379/0
  REDIS_URL: redis://plane-redis.plane.svc.cluster.local:6379/0
  CELERY_BROKER_URL: redis://plane-redis.plane.svc.cluster.local:6379/1
  CELERY_RESULT_BACKEND: redis://plane-redis.plane.svc.cluster.local:6379/2
  CELERY_WORKER_QUEUE: celery
  pgdb_remote_url: postgresql://plane:plane2026Secure@plane-postgresql.plane.svc.cluster.local:5432/plane
  DATABASE_URL: postgresql://plane:plane2026Secure@plane-postgresql.plane.svc.cluster.local:5432/plane
  PLANE_URL: https://plane.ebruno.fr
  GITEA_HOST: https://gitea.ebruno.fr
  docstore_bucket: uploads

external_secrets:
  pgdb_existingSecret: plane-postgresql-auth
  gitea_existingSecret: plane-gitea-oauth

ssl:
  enabled: true
  tls_secret_name: plane-tls

worker:
  memoryLimit: 4Gi
  cpuLimit: 1000m
  cpuRequest: 250m
  memoryRequest: 1024Mi

api:
  memoryLimit: 4Gi
  cpuLimit: 1000m
  cpuRequest: 250m
  memoryRequest: 1024Mi

beatworker:
  memoryLimit: 4Gi
  cpuLimit: 1000m
  cpuRequest: 250m
  memoryRequest: 1024Mi
  replicas: 1

replicas: 1

autoscaling:
  enabled: false
