{
 "title": "Harbor",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "harbor health",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "harbor health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte",
     "legendFormat": "{{ project_name }}"
    }
   ]
  },
  {
   "title": "artifact pulled",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(harbor_artifact_pulled[5m])",
     "legendFormat": "{{ project_name }} "
    }
   ]
  },
  {
   "title": "Projects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(harbor_project_total)" }
   ]
  },
  {
   "title": "Repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(harbor_project_repo_total)" }
   ]
  },
  {
   "title": "Public Projects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(harbor_project_total{public=\"true\"})"
    }
   ]
  },
  {
   "title": "Public Repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_project_repo_total{public=\"true\"})"
    }
   ]
  },
  {
   "title": "Private Projects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_project_total{public=\"false\"})"
    }
   ]
  },
  {
   "title": "Private Repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_project_repo_total{public=\"false\"})"
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core request inflight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(harbor_core_http_inflight_requests) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Core request operatoration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(harbor_core_http_request_total[5m])) by (operation)",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "max request time 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(harbor_core_http_request_duration_seconds{quantile=\"0.99\"}) by (operation)",
       "legendFormat": "{{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "task latency",
     "type": "graph",
     "description": "time period from last process of task queue",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(harbor_task_queue_latency) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "task concurrency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(harbor_task_concurrency) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "task queue pending size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_size", "legendFormat": "{{ type }}" }
     ]
    },
    {
     "title": "number of running scheduled job",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_scheduled_total", "legendFormat": " " }
     ]
    },
    {
     "title": "tasks per minute - fail",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(harbor_jobservice_task_total{status=\"fail\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "max task process time 0.99 - fail",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(harbor_jobservice_task_process_time_seconds{quantile=\"0.99\", status=\"fail\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "tasks per minute - success",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(harbor_jobservice_task_total{status=\"success\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "max task process time 0.99 - success",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(harbor_jobservice_task_process_time_seconds{quantile=\"0.99\", status=\"success\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(registry_http_in_flight_requests) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Registry request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_http_requests_total[5m])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "registry storage cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_cache_total[5m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "registry request time 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "registry request size 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, rate(registry_http_request_size_bytes_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "registry response size 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, rate(registry_http_response_size_bytes_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  }
 ]
}