{
 "title": "Loki-Promtail",
 "description": "an example for loki and promtail.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loki",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(loki_distributor_bytes_received_total[5m]))",
     "legendFormat": "Bytes Receiced"
    },
    {
     "expr": "sum (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "Lines Received"
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(promtail_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (rate(promtail_sent_bytes_total[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum (rate(promtail_encoded_bytes_total[5m]))",
     "legendFormat": "encoded"
    },
    {
     "expr": "sum(promtail_file_bytes_total - promtail_read_bytes_total)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promtail_file_bytes_total - promtail_read_bytes_total > 100000",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}