{
 "title": "PostgreSQL Tuple Statistics (Designed for PMM)",
 "description": "The PostgreSQL Tuple Statistics Dashboard",
 "tags": [ "postgresql" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,instance)" },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{instance=\"$host\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "relname",
    "label": "Table",
    "query": "label_values(pg_stat_user_tables_seq_tup_read{datname=~\"$db\"},relname)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1><br>"
  },
  { "title": "$host Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Tuple Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_database_tup_deleted{instance=\"$host\",datname=~\"$db\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}} - Deletes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_database_tup_inserted{instance=\"$host\",datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}} - Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_database_tup_updated{instance=\"$host\",datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}} - Updates"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_database_tup_fetched{instance=\"$host\",datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}} - Reads"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=~\"$db\",instance=\"$host\"}[$interval]) or\nirate(pg_stat_database_tup_returned{datname=~\"$db\",instance=\"$host\"}[5m])",
     "legendFormat": "{{datname}} - Returns"
    }
   ]
  },
  {
   "title": "$host Statistic per Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_idx_tup_fetch{instance=\"$host\", datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_idx_tup_fetch{instance=\"$host\", datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sequential Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_seq_tup_read{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_seq_tup_read{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inserts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_ins{instance=\"$host\",datname=~\"$db\"}[$interval]) or \nirate(pg_stat_user_tables_n_tup_ins{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_upd{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_n_tup_upd{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HOT Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{instance=\"$host\", datname=~\"$db\"}[$interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Deletes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_del{instance=\"$host\", datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_n_tup_del{instance=\"$host\", datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$host Dead Tuples per Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dead Tuples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(pg_stat_user_tables_n_dead_tup{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_user_tables_n_dead_tup{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Dead Tuples Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(pg_stat_user_tables_n_dead_tup{instance=\"$host\",datname=~\"$db\"}) / \n(pg_stat_user_tables_n_dead_tup{instance=\"$host\",datname=~\"$db\"} \n+ pg_stat_user_tables_n_live_tup{instance=\"$host\",datname=~\"$db\"})",
       "legendFormat": "{{datname}} - {{relname}}"
      }
     ]
    },
    {
     "title": "Live Tuples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(pg_stat_user_tables_n_live_tup{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_user_tables_n_live_tup{instance=\"$host\",datname=~\"$db\"}[5m])",
       "legendFormat": "{{datname}} - {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$host Vacuum/Autovacuum & Analyze/Autoanalyze per Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Autovacuum Per Table",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_user_tables_autovacuum_count{datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_autovacuum_count{datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Autovacuum",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "time() - pg_stat_user_tables_last_autovacuum{instance=~\"$host\", datname=~\"$db\"}"
      }
     ]
    },
    {
     "title": "Vacuum Per Table",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_user_tables_vacuum_count{datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_vacuum_count{datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Vacuum",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "time() - pg_stat_user_tables_last_vacuum{instance=~\"$host\", datname=~\"$db\"}"
      }
     ]
    },
    {
     "title": "Autoanalyze Per Table",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_user_tables_autoanalyze_count{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_autoanalyze_count{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Autoanalyze",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "time() - pg_stat_user_tables_last_autoanalyze{instance=~\"$host\", datname=~\"$db\"}"
      }
     ]
    },
    {
     "title": "Analyze Per Table",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_user_tables_analyze_count{instance=\"$host\",datname=~\"$db\"}[$interval]) or\nirate(pg_stat_user_tables_analyze_count{instance=\"$host\",datname=~\"$db\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{datname}} - {{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Analyze",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "time() - pg_stat_user_tables_last_analyze{instance=~\"$host\", datname=~\"$db\"}"
      }
     ]
    }
   ]
  }
 ]
}