apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-creds
  namespace: arc-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: arc-github-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        github_token: '{{ .github_token }}'
  dataFrom:
    - extract:
        key: github/arc-runner
