apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-creds
  namespace: arc-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 24h
  target:
    name: arc-github-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        github_app_id: '{{ .github_app_id }}'
        github_app_installation_id: '{{ .github_app_installation_id }}'
        github_app_private_key: '{{ .github_app_private_key }}'
  dataFrom:
    - extract:
        key: github/arc-app
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
