apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-github-creds-external-secret.yaml
  - crds/actions.github.com_autoscalinglisteners.yaml
  - crds/actions.github.com_autoscalingrunnersets.yaml
  - crds/actions.github.com_ephemeralrunners.yaml
  - crds/actions.github.com_ephemeralrunnersets.yaml
