server:
  extraArgs:
    oidc.config: |
      issuer: https://keycloak.ebruno.fr/realms/platform
      clientID: argocd
      clientSecret: $ARGOCD_SERVER_OIDC_CLIENT_SECRET
      rootCA:
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  extraEnv:
    - name: OAUTH2_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: argocd-oidc-secrets
          key: CLIENT_SECRET_ARGOCD
    - name: ARGOCD_SERVER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argocd-oidc-secrets
          key: CLIENT_SECRET_ARGOCD
    - name: OAUTH2_SECRET
      valueFrom:
        secretKeyRef:
          name: argocd-oidc-secrets
          key: CLIENT_SECRET_ARGOCD
