name: renovate

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  security-events: read

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: renovate/renovate:latest
      options: --user 0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run Renovate
        run: renovate --platform github ebpro/gitops
